/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceServiceKeyRouteImport } from './routes/service.$serviceKey'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceServiceKeyRoute = ServiceServiceKeyRouteImport.update({
  id: '/service/$serviceKey',
  path: '/service/$serviceKey',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/service/$serviceKey': typeof ServiceServiceKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/service/$serviceKey': typeof ServiceServiceKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/service/$serviceKey': typeof ServiceServiceKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/service/$serviceKey'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/service/$serviceKey'
  id: '__root__' | '/' | '/service/$serviceKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServiceServiceKeyRoute: typeof ServiceServiceKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$serviceKey': {
      id: '/service/$serviceKey'
      path: '/service/$serviceKey'
      fullPath: '/service/$serviceKey'
      preLoaderRoute: typeof ServiceServiceKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServiceServiceKeyRoute: ServiceServiceKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
